// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" }
import * as $0 from "./routes/_404.jsx"
import * as $1 from "./routes/_500.jsx"
import * as $2 from "./routes/_middleware.js"
import * as $3 from "./routes/index.jsx"
import * as $4 from "./routes/sitemap.xml.js"

const manifest = {
  routes: {
    "./routes/_404.jsx": $0,
    "./routes/_500.jsx": $1,
    "./routes/_middleware.js": $2,
    "./routes/index.jsx": $3,
    "./routes/sitemap.xml.js": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
}

export default manifest
